name: Production deployment

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: cd-with-actions
  AZURE_APP_PLAN: actions-web-deployment
  AZURE_LOCATION: '"East Asia"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: pfchuang-web-app
  #################################################
